version: '3.7'
services:
  api:
    image: node:18-alpine
    container_name: comments-api
    hostname: comment-api.docker
    command: "sh -c 'cd /app && npm i && npm run start:dev'"
    environment:
      - NODE_ENV=dev
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - IS_OFFLINE=""
    volumes:
      - ./comments-api:/app
      - ./comments-api/docker.env:/app/.env
    ports:
      - 3001:3000

  app:
    image: node:18-alpine
    container_name: comments-app

    command: "sh -c 'cd /app && npm i && npm run dev'"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./comments-front:/app
      - ./comments-front/docker.env:/app/.env
    ports:
      - 3000:3000
  
  dynamodb:
    image: amazon/dynamodb-local
    container_name: comments-app-dynamodb
    hostname: dynamodb.docker
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data
    ports:
      - 8001:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
